# Estágio de Build
FROM node:20-alpine AS builder
WORKDIR /app

# Build args (Easypanel e outras plataformas injetam essas variáveis no build)
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ARG EVOLUTION_API_URL
ARG EVOLUTION_API_KEY
ARG EVOLUTION_INSTANCE
ARG OPENAI_API_KEY
ARG DATABASE_URL
ARG LANGGRAPH_CHECKPOINT_POSTGRES_URI

ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV EVOLUTION_API_URL=$EVOLUTION_API_URL
ENV EVOLUTION_API_KEY=$EVOLUTION_API_KEY
ENV EVOLUTION_INSTANCE=$EVOLUTION_INSTANCE
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV DATABASE_URL=$DATABASE_URL
ENV LANGGRAPH_CHECKPOINT_POSTGRES_URI=$LANGGRAPH_CHECKPOINT_POSTGRES_URI

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Estágio de Produção
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV production

COPY --from=builder /app/next.config.ts ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

EXPOSE 3000
CMD ["npm", "start"]